version: "3.3"

services:
  api:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: api, tasks, sentry
      PORT: 4040
    ports:
      - "4040:4040"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=mp-development"
      - "traefik.port=4040"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:dev.mp.knawat.io"

  stores:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: stores

  products-instances:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: products-instances

  products:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: categories, products

  currencies:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: currencies, taxes, gdpr

  subscription:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: membership, subscription, coupons, crm

  subscription-cron:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: subscription-cron

  orders:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: orders

  invoices:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: invoices, payments

  oms:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: oms

  shipment:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: shipment

  logs:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: logs

  redis:
    image: redis:alpine

  traefik:
    image: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
