version: '3.3'

services:
  api:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: api
      PORT: 4040
    ports:
      - '4040:4040'
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=mp-development'
      - 'traefik.port=4040'
      - 'traefik.frontend.entryPoints=http,https'
      - 'traefik.frontend.rule=Host:dev.mp.knawat.io'

  stores:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      SERVICES: stores

  users:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: users

  invoices:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: invoices, payments

  subscription-cron:
      build:
        context: ../../
      image: microes
      restart: always
      env_file: .env
      environment:
        SERVICES: subscription-cron

  catalog:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: products
    networks:
      - elastic
      - default

  list:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: categories, products-list
    networks:
      - elastic
      - default

  logs:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: logs
    networks:
      - elastic
      - default

  orders:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: orders

  shipment:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      SERVICES: shipment

  currencies:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: currencies

  subscription:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: membership, subscription, coupons

  elastic-update:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: elastic-update
    volumes:
      - ~/data/mp-nedb:/app/data
    networks:
      - elastic
      - default

  redis:
    image: redis:alpine

  nats:
    image: nats

  mongodb:
    image: mongo:4
    restart: always
    env_file: .env
    volumes:
      - ~/data/db/mp-dev:/data/db
      - ../docker-mongodb-init/:/docker-entrypoint-initdb.d/
    ports:
      - '21985:27017'

  traefik:
    image: traefik
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    networks:
      - elastic
      - default

networks:
  elastic:
    external:
      name: elk-dev_default
