version: '3.3'

services:
  api:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: api
      PORT: 4040
    ports:
      - '4040:4040'
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=mp-development'
      - 'traefik.port=4040'
      - 'traefik.frontend.entryPoints=http,https'
      - 'traefik.frontend.rule=Host:dev.mp.knawat.io'

  users:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: users

  catalog:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: products,categories

  orders:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: orders
