version: "3.0"

services:

  api:
    build:
      context: ../../
    image: conduit
    restart: always
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    links:
      - nats
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"
      - "traefik.backend=development"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=PathPrefix:/"

  users:
    build:
      context: ../../
    image: conduit
    restart: always
    env_file: docker-compose.env
    environment:
      SERVICES: users
    links:
      - nats
    depends_on:
      - nats

  products:
    build:
      context: ../../
    image: conduit
    restart: always
    env_file: docker-compose.env
    environment:
      SERVICES: products,categories
    links:
      - nats
    depends_on:
      - nats

  orders:
    build:
      context: ../../
    image: conduit
    restart: always
    env_file: docker-compose.env
    environment:
      SERVICES: orders
    links:
      - nats
    depends_on:
      - nats

  nats:
    image: nats

  traefik:
    image: traefik
    restart: always
    ports:
      - "4040:80"
      - "4044:443"
      - "4444:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../traefik.toml:/traefik.toml
      - ../acme.json:/acme.json

