version: "3.0"

services:

  api:
    build:
      context: ../../
    image: conduit
    restart: always
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 4040
    ports:
      - "4040:4040"
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=mp-development"
      - "traefik.port=4040"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:dev.mp.knawat.io"
      - "traefik.docker.network=traefik_default"

  users:
    build:
      context: ../../
    image: conduit
    restart: always
    env_file: docker-compose.env
    environment:
      SERVICES: users

  catalog:
    build:
      context: ../../
    image: conduit
    restart: always
    env_file: docker-compose.env
    environment:
      SERVICES: products,categories

  orders:
    build:
      context: ../../
    image: conduit
    restart: always
    env_file: docker-compose.env
    environment:
      SERVICES: orders

networks:
  traefik:
    external:
      name: traefik_default
