version: "3.3"

services:
  api:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: api, tasks
      PORT: 4040
    ports:
      - "4040:4040"
    labels:
      traefik.enable: "true"
      traefik.backend: mp-development
      traefik.port: 4040
      traefik.frontend.entryPoints: "http,https"
      traefik.frontend.rule: "Host:dev.mp.knawat.io"
      com.datadoghq.ad.logs: '[{"source": "mp", "service": "api"}]'

  stores:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: stores
    labels:
      com.datadoghq.ad.logs: '[{"source": "mp", "service": "stores"}]'

  products-instances:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: products-instances
    labels:
      com.datadoghq.ad.logs: '[{"source": "mp", "service": "products-instances"}]'

  products:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: categories, products
    labels:
      com.datadoghq.ad.logs: '[{"source": "mp", "service": "products"}]'

  currencies:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: currencies, taxes, gdpr
    labels:
      com.datadoghq.ad.logs: '[{"source": "mp", "service": "currencies"}]'

  subscription:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: membership, subscription, coupons, crm
    labels:
      com.datadoghq.ad.logs: '[{"source": "mp", "service": "subscription"}]'

  subscription-cron:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: subscription-cron
    labels:
      com.datadoghq.ad.logs: '[{"source": "mp", "service": "subscription-cron"}]'

  orders:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: orders
    labels:
      com.datadoghq.ad.logs: '[{"source": "mp", "service": "orders"}]'

  invoices:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: invoices, payments
    labels:
      com.datadoghq.ad.logs: '[{"source": "mp", "service": "invoices"}]'

  oms:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: oms
    labels:
      com.datadoghq.ad.logs: '[{"source": "mp", "service": "oms"}]'

  shipment:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: shipment
    labels:
      com.datadoghq.ad.logs: '[{"source": "mp", "service": "shipment"}]'

  logs:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: logs
    labels:
      com.datadoghq.ad.logs: '[{"source": "mp", "service": "logs"}]'

  redis:
    image: redis:alpine
    labels:
      com.datadoghq.ad.logs: '[{"source": "mp", "service": "redis"}]'

  traefik:
    image: traefik:v1.7
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    labels:
      com.datadoghq.ad.logs: '[{"source": "mp", "service": "traefik"}]'

  datadog:
    build: ../datadog
    env_file: .env
    links:
      - api
      - stores
      - products-instances
      - products
      - currencies
      - subscription
      - subscription-cron
      - orders
      - invoices
      - oms
      - shipment
      - logs
      - redis
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /sys/kernel/debug:/sys/kernel/debug
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
      - SYS_PTRACE
      - NET_ADMIN
      - IPC_LOCK
    security_opt:
      - apparmor:unconfined
