version: "3.3"

services:
  api:
    build:
      context: ../../
    image: mp
    restart: always
    env_file: .env
    hostname: "api"
    environment:
      SERVICES: api, tasks
      PORT: 4040
    labels:
      traefik.enable: "true"
      traefik.backend: mp-development
      traefik.port: 4040
      traefik.frontend.entryPoints: "http,https"
      traefik.frontend.rule: "Host:dev.mp.knawat.io"
      traefik.docker.network: mp_default

  stores:
    build:
      context: ../../
    image: mp
    restart: always
    env_file: .env
    hostname: "stores"
    environment:
      SERVICES: stores

  products-instances:
    build:
      context: ../../
    image: mp
    restart: always
    env_file: .env
    hostname: "products-instances"
    environment:
      SERVICES: products-instances, products

  categories:
    build:
      context: ../../
    image: mp
    restart: always
    env_file: .env
    hostname: "categories"
    environment:
      SERVICES: categories

  currencies:
    build:
      context: ../../
    image: mp
    restart: always
    env_file: .env
    hostname: "currencies-taxes-gdpr"
    environment:
      SERVICES: currencies, taxes, gdpr

  subscription:
    build:
      context: ../../
    image: mp
    restart: always
    env_file: .env
    hostname: "membership-subscription-coupons"
    environment:
      SERVICES: membership, subscription, coupons

  subscription-cron:
    build:
      context: ../../
    image: mp
    restart: always
    env_file: .env
    hostname: "subscription-cron"
    environment:
      SERVICES: subscription-cron

  orders:
    build:
      context: ../../
    image: mp
    restart: always
    env_file: .env
    hostname: "orders"
    environment:
      SERVICES: orders

  invoices:
    build:
      context: ../../
    image: mp
    restart: always
    env_file: .env
    hostname: "invoices-payments"
    environment:
      SERVICES: invoices, payments

  oms:
    build:
      context: ../../
    image: mp
    restart: always
    env_file: .env
    hostname: "oms"
    environment:
      SERVICES: oms

  shipment:
    build:
      context: ../../
    image: mp
    restart: always
    env_file: .env
    hostname: "shipment"
    environment:
      SERVICES: shipment

  redis-cacher:
    image: redis:alpine

  redis-transporter:
    image: redis:alpine

  redis-admin:
    image: erikdubbelboer/phpredisadmin
    env_file: .env
    environment:
      - ADMIN_USER=$BASIC_USER
      - ADMIN_PASS=$BASIC_PASS
      - REDIS_1_HOST=redis-cacher
      - REDIS_1_PORT=6379
    ports:
      - "6379:80"

  traefik:
    image: traefik:v1.7
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/acme.json

  monitor:
    build:
      context: ../../
    image: mp
    restart: always
    env_file: .env
    hostname: "monitor"
    environment:
      SERVICES: apm, lab
    ports:
      - "3210:3210"
