# defaultEntryPoints must be at the top because it should not be in any table below
defaultEntryPoints = ["http", "https"]

## Logs
debug = false
logLevel = "ERROR"

# Entrypoints, http and https
[entryPoints]

# http should be redirected to https
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"

# https is the default
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

# Enable ACME (Let's Encrypt): automatic SSL
[acme]
email = "it@knawat.com"
storage = "acme.json" # or "traefik/acme/account" if using KV store
entryPoint = "https"
onHostRule = true
acmeLogging = true

[acme.httpChallenge]
entryPoint = "http"

[[acme.domains]]
main = "suppliers.knawat.io"
sans = ["dev.suppliers.knawat.io"]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "suppliers.knawat.io"
watch = true
exposedByDefault = false
