version: '3.3'

services:
  api:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: api
      PORT: 80
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=production'
      - 'traefik.port=80'
      - 'traefik.frontend.entryPoints=http,https'
      - 'traefik.frontend.rule=Host:mp.knawat.io'
  es:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: es
    networks:
      - elastic
      - default

  klayer:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: klayer

  stores:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: stores

  users:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: users
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis

  catalog:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: products,categories
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis
    networks:
      - elastic
      - default

  orders:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: orders
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis

  currencies:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: currencies
    volumes:
      - ../../data:/app/data

  shipment:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: shipment
    depends_on:
      - mongodb
    links:
      - mongodb

  elastic-update:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: elastic-update
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis
    volumes:
      - ../../data:/app/data
    networks:
      - elastic
      - default

  mongodb:
    image: mongo:4
    restart: always
    env_file: .env
    volumes:
      - ~/data/db/mp:/data/db
      - ../docker-mongodb-init/:/docker-entrypoint-initdb.d/
    ports:
      - '21985:27017'

  redis:
    image: redis:alpine

  nats:
    image: nats

  traefik:
    image: traefik
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json

networks:
  elastic:
    external:
      name: dockerelk_elk
