version: '3.3'

services:
  api:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: api, tasks
      PORT: 80
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=production'
      - 'traefik.port=80'
      - 'traefik.frontend.entryPoints=http,https'
      - 'traefik.frontend.rule=Host:mp.knawat.io'

  stores:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: stores
    depends_on:
      - mongodb

  product-instances:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: products-instances

  products:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: categories, products

  currencies:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: currencies, taxes, gdpr

  subscription:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: membership, subscription, coupons, crm

  subscription-cron:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: subscription-cron

  orders:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: orders

  invoices:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: invoices, payments

  shipment:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: shipment
    depends_on:
      - mongodb

  oms:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: oms

  logs:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    environment:
      SERVICES: logs

  redis:
    image: redis:alpine

  mongodb:
    image: mongo:4
    restart: always
    env_file: .env
    volumes:
      - ~/data/db/mp:/data/db
      - ../docker-mongodb-init/:/docker-entrypoint-initdb.d/
    ports:
      - '21985:27017'

  traefik:
    image: traefik
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
