version: "3.3"

services:
  api:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    hostname: "api"
    environment:
      SERVICES: api, tasks
      PORT: 4040
    labels:
      traefik.enable: "true"
      traefik.backend: mp-development
      traefik.port: 4040
      traefik.frontend.entryPoints: "http,https"
      traefik.frontend.rule: "Host:dev.mp.knawat.io"

  stores:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    hostname: "stores"
    environment:
      SERVICES: stores

  products-instances:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    hostname: "products-instances"
    environment:
      SERVICES: products-instances

  products:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    hostname: "categories-products"
    environment:
      SERVICES: categories, products

  currencies:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    hostname: "currencies-taxes-gdpr"
    environment:
      SERVICES: currencies, taxes, gdpr

  subscription:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    hostname: "membership-subscription-coupons-crm"
    environment:
      SERVICES: membership, subscription, coupons, crm

  subscription-cron:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    hostname: "subscription-cron"
    environment:
      SERVICES: subscription-cron

  orders:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    hostname: "orders"
    environment:
      SERVICES: orders

  invoices:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    hostname: "invoices-payments"
    environment:
      SERVICES: invoices, payments

  oms:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    hostname: "oms"
    environment:
      SERVICES: oms

  shipment:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    hostname: "shipment"
    environment:
      SERVICES: shipment

  redis:
    image: redis:alpine

  traefik:
    image: traefik:v1.7
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json

  monitor:
    build:
      context: ../../
    image: microes
    restart: always
    env_file: .env
    hostname: "monitor"
    environment:
      SERVICES: apm, lab
    ports:
      - "3210:3210"
