version: "3.0"

services:

  api:
    container_name: mp_api
    build:
      context: ../../
    image: conduit
    restart: always
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 80
    links:
      - nats
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"
      - "traefik.backend=production"
      - "traefik.port=80"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:mp.knawat.io"

  users:
    container_name: mp_users
    build:
      context: ../../
    image: conduit
    restart: always
    env_file: docker-compose.env
    environment:
      SERVICES: users
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis

  products:
    container_name: mp_catalog
    build:
      context: ../../
    image: conduit
    restart: always
    env_file: docker-compose.env
    environment:
      SERVICES: products,categories
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis
    networks:
      - default
      - elastic

  orders:
    container_name: mp_orders
    build:
      context: ../../
    image: conduit
    restart: always
    env_file: docker-compose.env
    environment:
      SERVICES: orders
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis

  redis:
    image: redis:alpine

  nats:
    image: nats

  traefik:
    container_name: mp_traefik
    image: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json

networks:
  elastic:
    external:
      name: dockerelk_elk
