FROM datadog/agent:latest
ADD datadog.yaml /etc/datadog-agent/datadog.yaml
ADD conf.d/redisdb.yaml /etc/datadog-agent/conf.d/redisdb.yaml
ADD conf.d/docker_daemon.yaml conf.d/docker.d/docker_daemon.yaml
